package com.example.teamwork.constant;

import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;

public class Constant {
	public static final Long ID_1 = 1L;
	public static final Long ID_2 = 2L;
	public static final Long ID_3 = 3L;
	public static final Long CHAT_ID_1 = 11L;
	public static final Long CHAT_ID_2 = 22L;
	public static final Long CHAT_ID_3 = 33L;
	public static final String FULL_NAME_1 = "name1";
	public static final String FULL_NAME_2 = "name2";
	public static final String FULL_NAME_3 = "name3";
	public static final Integer EXPERIENCE_1 = 11;
	public static final Integer EXPERIENCE_2 = 22;
	public static final String PHONE_NUMBER_1 = "89171111111";
	public static final String PHONE_NUMBER_2 = "89172222222";
	public static final String PHONE_NUMBER_3 = "89173333333";
	public static final String EMAIL_1 = "email1@mail.ru";
	public static final String EMAIL_2 = "email2@mail.ru";
	public static final String EMAIL_3 = "email3@mail.ru";
	public static final String COMMENTS_1 = "text1";
	public static final String COMMENTS_2 = "text2";
	public static final String COMMENTS_3 = "text3";
	public static final Long VOLUNTEER_ID_1 = 11L;
	public static final Long VOLUNTEER_ID_2 = 22L;
	public static final Long VOLUNTEER_ID_3 = 33L;
	public static final Long ADOPTERS_CHAT_ID_1 = 112233L;
	public static final Long ADOPTERS_CHAT_ID_2 = 223344L;
	public static final Long DOG_ID_1 = 11L;
	public static final Long DOG_ID_2 = 22L;
	public static final Long ADOPTER_ID_1 = 111L;
	public static final Long ADOPTER_ID_2 = 222L;
	public static final Integer TRIAL_PERIOD_1 = 30;
	public static final Integer TRIAL_PERIOD_2 = 14;
	public static final LocalDateTime REGISTRATION_DATE_1 = LocalDateTime.now().truncatedTo(ChronoUnit.DAYS).minusDays(1);
	public static final LocalDateTime REGISTRATION_DATE_2 = LocalDateTime.now().truncatedTo(ChronoUnit.DAYS);
	public static final LocalDateTime LAST_DATE_OF_REPORTS_1 = LocalDateTime.now().truncatedTo(ChronoUnit.DAYS);
	public static final LocalDateTime LAST_DATE_OF_REPORTS_2 = LocalDateTime.now().truncatedTo(ChronoUnit.DAYS);
	public static final String NAME = "name1";
	public static final Integer AGE = 1;
	public static final Disability DISABILITY = Disability.MOVEMENT;
	public static final String COMMENTS = "text1";
	public static final Long CHAT_ID = 334455L;
	public static final String FULL_NAME = "name";
	public static final String PHONE_NUMBER = "89171112233";
	public static final String NAME_1 = "name1";
	public static final String NAME_2 = "name2";
	public static final String NAME_3 = "name3";
	public static final Integer AGE_1 = 1;
	public static final Integer AGE_2 = 2;
	public static final Integer AGE_3 = 3;
	public static final Disability DISABILITY_1 = Disability.MOVEMENT;
	public static final Disability DISABILITY_2 = Disability.INTERNAL;
	public static final Disability DISABILITY_3 = Disability.NO;
	public static final LocalDateTime REQUEST_TIME_1 = LocalDateTime.now().truncatedTo(ChronoUnit.DAYS).minusDays(1);
	public static final LocalDateTime REQUEST_TIME_2 = LocalDateTime.now().truncatedTo(ChronoUnit.DAYS);
	public static final LocalDateTime REQUEST_TIME_3 = LocalDateTime.now().truncatedTo(ChronoUnit.DAYS).plusDays(1);
	public static final Long DOG_VOLUNTEER_ID_1 = 11L;
	public static final Long DOG_VOLUNTEER_ID_2 = 22L;
	public static final Long DOG_VOLUNTEER_ID_3 = 33L;
	public static final String FILE_NAME_1 = "name1";
	public static final String FILE_NAME_2 = "name2";
	public static final String DESCRIPTION_1 = "text1";
	public static final String DESCRIPTION_2 = "text2";
	public static final LocalDateTime DISPATCH_TIME_1 = LocalDateTime.now().truncatedTo(ChronoUnit.DAYS);
	public static final LocalDateTime DISPATCH_TIME_2 = LocalDateTime.now().truncatedTo(ChronoUnit.DAYS).minusDays(1);
	public static final boolean REPORTS_STATUS_1 = true;
	public static final boolean REPORTS_STATUS_2 = false;
	public static final String FILENAME_JSON_TEXT = "text_update.json";
	public static final String FILENAME_JSON_DATA = "data_update.json";
	public static final String FILENAME_JSON_PHOTO = "photo_update.json";
	public static final String PATH_TO_JSON_FILE = "src/test/resources/";
	public static final Long BTN_FROM_ID = 1122334455L;
	public static final Long MSG_CHAT_ID = 9876543210L;

}
